# Docker Compose configuration for UK Life Insurance Calculator

services:
  insurance-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lloyds-insurance-calculator
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Europe/London
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    volumes:
      - ./logs:/app/logs
      - ./src/main/resources/application.yml:/app/application.yml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/lloyds-insurance-calculator/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - insurance-network



networks:
  insurance-network:
    driver: bridge

volumes:
  logs:
    driver: local 